### ISSUE TITLE
Clarify Hardware, Purpose of Code, and Development Environment

### ISSUE THREAD

**Issue by BobCochran** [nanofortran/i2cAdafruitLCD#3]
Hi Jason,

I want to make sure I understand how to use your i2cAdafruitLCD project code. Can you correct me if I am wrong?

You have a Raspberry Pi 2 Model B device, and within this you are running a version of Node.js. The Raspberry Pi device is connected to the i2c backpack you have from AdaFruit. You are using the Raspberry Pi's resources and implementation of Node plus the code in this repository in order to connect to the i2c controller and send data to the character LCD. 

Is the above summary correct? That is the "picture" I have in my mind. In other words, you are doing all your development for this project inside your Raspberry Pi 2? Is that correct?

What operating system are you running on you Raspberry Pi 2? Is it up-to-date?

What version of Node.js are you running in the Raspberry Pi 2? 

What LCD part are you using? Did you buy it from Adafruit?

I have two Raspberry Pi devices, one is pretty old and one is more recent. I am not sure if the newer device is the Raspberry Pi 2. I'll check to see if I can emulate your work on either of my devices. I'm preparing an order today with Adafruit for the i2c backpack you use. 

Thanks a ton!

Bob Cochran

**Comment by nanofortran** [comment]
Hey Bob:

That picture seems correct to me (I should add some images to the README to provide visual confirmation).

Yes, it is a Raspberry Pi 2 Model B which has node.js running on it. I am running node 4.2.1 and all the development has been done on the Pi. The operating system is 8.0 (Jessie).

For my project I am using the RGB LCDs from Adafruit (Item # 399). Since there are 3 LEDs in there providing the red/green/blue components for the back light plate, there is one pin per color. I don't recall off the top of my head, but I think there is a single positive pin and then you ground the R, G, or B pin to pick your color. Of course, you can also mix the colors using PWM, which is the second part of my project using an spi expander, but I will work on that next month.

However, you can use any LCD you wish that use the HD44780 ic. Even the four line versions such as here: https://www.adafruit.com/products/198 . . . and extending the library to accommodate other configurations of LCDs should not be a problem (as long as they use the HD44780). We just need to do a bit of research on what nibbles need to be set to push the cursor to those lines.

I wish to change the names of some of the functions, to make them more intuitive, and I have yet to try this with more than 1 LCD . . . my project uses 12 and I am planning on running it via 2 PiZeros . . . so, more to do . . .

Chat soon and thanks.

Jason

**Comment by BobCochran** [comment]
Hey Jason:

Thank you. I checked my Raspberry Pi collection. The most recent model I own is the Model B+. I'm going to try running the project on that. I ordered some parts from Amazon and I'm almost ready with an order from Adafruit. Somewhere around here I have a HD44780-based LCD. 

I will follow what you do with your project with great interest. I'm able to sync this Github repository to my local repository (the one I have on my computer), so any changes you update to GitHub for this project will also flow to me. From my perspective you are my "upstream" repository, and I can 'git fetch upstream' right on the command line and then merge them into my 'master' branch. Which I can then push to my own GitHub repository.

One of the magic things about Git is that you can have any number of software "branches" in a repository. That means you can test out all the ideas you have simply by creating a new branch on your local repository and switching to that and working inside it. Then later, if you want, you can merge branches back into your master branch. So you can have code for many different ideas or scenarios and you can play with all of them without breaking your master branch. Give it a try, you will get to like Git a lot. And no, I don't work for either Github or Linus Torvalds. (Smile.)

Happy coding and IoT'ing to you!

Bob

**Comment by nanofortran** [comment]
thanks!
